### ISSUE TITLE
Police count doesnt seem to work 

### ISSUE THREAD

**Issue by Nick5M420** [ItsSlappy/sp-MeterRobbery#1]
i had it set to "1" police there was 3 online and it didnt let them hit it unless it was set to 0

**Comment by fimg2021** [comment]
I have the same problem

**Comment by ImMacky** [comment]
Apologies for the late response.

We will investigate this issue later today once we are available.

**Comment by ImMacky** [comment]
With the most recent release (Version 1.2), you won't encounter this problem anymore.
