### ISSUE TITLE
3rd Eye isn't working on the meter

### ISSUE THREAD

**Issue by staxxxcash** [ItsSlappy/sp-MeterRobbery#2]
![image](https://github.com/ItsSlappy/sp-MeterRobbery/assets/133084518/0d77c43e-df09-4a3f-b606-21d7bef8e323)
this shi broken or sum jus someone help me please.

**Comment by ImMacky** [comment]
Apologies for the late response.

We will investigate this issue later today once we are available.

**Comment by ImMacky** [comment]
I've tested the script on both the most recent QBCore Release and Artifacts versions, and I can confirm there are no errors. The issue you may be experiencing is likely due to not having a toolkit _(screwdriverset)_ on your character while third-eyeing the meter.
